### PR TITLE
fix ReadTheDocs configuration

### LINKED ISSUE #71: DOC: RTD cannot build due to outdated YAML
https://github.com/spacetelescope/stsci.skypac/blob/master/.readthedocs.yml needs to be updated to v2

### PR DESCRIPTION
**Pull request by zacharyburnett**
closes #71

### CODE REVIEW

**Comment by pllim** [comment]
Looks like `docs/source/conf.py` and possibly other related doc infrastructure also need updating.

**Comment by pllim** [comment]
Something still isn't right. Somehow it ended up trying to build with a very old Sphinx v1.8.5 even though it initially found modern Sphinx v7

**Comment by pllim** [comment]
Is this really necessary?

https://github.com/spacetelescope/stsci.skypac/blob/3a8d671fd2c25677fbb9014af2082399e53fb3fa/docs/source/conf.py#L207

**Comment by pllim** [comment]
I think it finally installed and trying to build the docs but has problem finding the namespace packages.

```
* ModuleNotFoundError: No module named 'stsci.tools'
* AttributeError: module 'stsci' has no attribute 'skypac'
```

**Comment by zacharyburnett** [comment]
ugh, another namespace issue. I'll take a look at this today

**Comment by pllim** [comment]
Thanks!

**Comment by zacharyburnett** [comment]
this is so odd 
```shell
❯ python -c "import stsci.tools"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'stsci.tools'
```

**Comment by pllim** [comment]
Looks like RTD had not built successfully for 2 years for this package. Probably have to clean up a bunch of tech debt first.

**Comment by pllim** [comment]
So looking at one of the warnings:

```
WARNING: Failed to import stsci.skypac.parseat.
Possible hints:
* ModuleNotFoundError: No module named 'stsci.tools'
* AttributeError: module 'stsci' has no attribute 'skypac'
```

And the actual content of `docs/source/parseat.rst`:

```rst
===========================================================
Utility functions for parsing user catalog files for skypac
===========================================================

.. moduleauthor:: Mihai Cara <help@stsci.edu>

.. currentmodule:: stsci.skypac.parseat

.. automodule:: stsci.skypac.parseat
   :members:
```

I feel like possible hints might be red herring. My hunch is you have to tweak either currentmodule, automodule, or both. At this point, try to build the doc locally with different tweaks until this warning goes away, and then apply similar patches to the other API docs.

p.s. moduleauthor is unnecessary and probably can be removed.

**Review by mcara — APPROVED** [review]
Could you please rebase this?

**Review by mcara — CHANGES_REQUESTED** [review]
Could you please rebase this?
