### PR TITLE
Improve numpy 2 compatibility

### LINKED ISSUE #79: DeprecationWarning with numpy >2.0
region.py:423: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)

As seen in drizzlepac tests.

[Another Warning i](https://github.com/spacetelescope/RegressionTests/actions/runs/16352978260/job/46204327143#step:35:55)n drizzlepac RT
tsci/skypac/skyline.py:900: SyntaxWarning: 'str' object is not callable; perhaps you missed a comma?
    raise AttributeError("'%s' object has no attribute '%s'"

### PR DESCRIPTION
**Pull request by mcara**
Improves numpy 2 compatibility (deprecation warnings).

Fixes #79.

### CODE REVIEW

**Comment by mcara** [comment]
Regression tests are running here: https://github.com/spacetelescope/RegressionTests/actions/runs/16913339733

**Comment by mcara** [comment]
Regression tests pass and I do not see deprecation warnings reported in #79
